version: '3.1'

services:
  mongo:
    container_name: mongo
    image: mongo
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: some-user
      MONGO_INITDB_ROOT_PASSWORD: some-pwd   
      MONGO_INITDB_DATABASE: test
    volumes: 
      - ./data/db:/data/db
      - ./docker-entrypoint-initdb.d/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
  mongo-express:
    container_name: mongo-express
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: some-user
      ME_CONFIG_MONGODB_ADMINPASSWORD: some-pwd
    
